config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'

  devise_scope :user do
    get 'login', to: 'users/sessions#new', as: :new_user_session
    post 'login', to: 'users/sessions#create', as: :user_session
    delete 'logout', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  devise_for :users, skip: [:sessions],
  controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  scope module: :users do
    resources :users, only:[:show,:edit,:update,:destroy]
    resources :items do
      resource :likes, only:[:create,:destroy]
      resources :comments, only:[:create,:update,:destroy]
    end
    resources :likes, only:[:index]
    resources :cart_items, only:[:index,:create,:update,:destroy] do
      collection do
        delete 'clear' # カートを空にする
      end
    end
    resources :orders, only:[:new,:index,:show,:create] do
      collection do
        get 'confirm'   # 購入情報確認画面
        post 'storage'  # セッションに保存
        get 'complete'  # 購入完了画面
        delete 'cancel' # 注文キャンセル
      end
    end
    resources :addresses, only:[:index,:create,:edit,:update,:destroy]
  end

  ######## 管理側 ########
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :admins do
    resources :items, only:[:edit,:update]
    resources :users, only:[:index,:show,:edit,:update,:destroy] do
      member do
        patch 'restore'
      end
    end
    resources :orders, only:[:index,:update,:show]
  end
  
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.page(params[:page]).per(20)
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    order = Order.find(params[:id])
    if params[:order_status_commit]
      order.update(order_params)
    elsif params[:production_status_commit]
      OrderDetail.find(params[:order_detail][:id]).update(order_detail_params)
    else
      render "show"
    end
    redirect_to admins_orders_url, flash: { success: "ステータスを更新しました" }
  end

  private

    def order_params
      params.require(:order).permit(:order_status)
    end

    def order_detail_params
      params.require(:order_detail).permit(:production_status)
    end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_user, only: [:edit, :update]

  def index
    @users = User.with_deleted.page(params[:page]).per(20)
  end

  def show
    @user = User.with_deleted.find(params[:id])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "ユーザー登録情報を更新しました"
      redirect_to admins_users_url
    else
      render "edit"
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to admins_users_url
  end

  def restore
    user = User.only_deleted.find(params[:id]).restore
    redirect_to admins_users_url
  end

  private

    def user_params
      params.require(:user).permit(
        :name,:email,:password,:password_confirmation,:last_name,:first_name,
        :last_name_kana,:first_name_kana,:postcode,:prefecture_name,:address_city,
        :address_street,:address_building,:telephone_number
      )
    end

    def set_user
      @user = User.find(params[:id])
    end

end

app/controllers/users/addresses_controller.rb
class Users::AddressesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_address, only: [:edit, :update]

  def index
    @address = Address.new
    @addresses = Address.where(user_id: current_user.id)
    @user = current_user
  end

  def create
    @address = current_user.addresses.build(address_params)
    @address.name = current_user.last_name
    if @address.save
      redirect_to addresses_url, flash: { success: "住所を登録できました！" }
    else
      @addresses = Address.where(user_id: current_user.id)
      @user = current_user
      render "index"
    end
  end

  def edit
  end

  def update
    if @address.update(address_params)
      redirect_to addresses_url, flash: { success: "登録していた住所を編集しました！"}
    else
      render "edit"
    end
  end

  def destroy
    Address.find(params[:id]).destroy
    redirect_to addresses_url, flash: { success: "登録していた住所を削除しました" }
  end

  private

    def set_address
      @address = Address.find(params[:id])
    end

    def address_params
      params.require(:address).permit(:postcode,:prefecture_name,:address)
    end
end

app/controllers/users/cart_items_controller.rb
class Users::CartItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cart_items, only:[:index]

  def index
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    if @cart_item.save
      flash[:success] = "カートに商品を入れました"
      redirect_to cart_items_url
    else
      @item = Item.find(params[:cart_item][:item_id])
      unless CartItem.find_by(user_id: params[:cart_item][:user_id],item_id: @item.id).nil?
        flash.now[:warning] = "この商品は既にお客様のカートに入れてあります"
      end
      render "users/items/show"
    end
  end

  def update
    cart_item = CartItem.find(params[:id])
    if cart_item.update(cart_item_params)
      flash[:success] = "#{cart_item.item.name}の数量を変更しました"
      redirect_to cart_items_url
    else
      flash.now[:danger] = "商品の数量を入力してください"
      set_cart_items
      render "index"
    end
  end

  def destroy
    cart_item = CartItem.find(params[:id])
    cart_item.destroy
    flash[:success] = "#{cart_item.item.name}をカートから削除しました"
    redirect_to cart_items_url
  end

  def clear
    CartItem.where(user_id: current_user.id).destroy_all
    flash[:success] = "カートを空にしました"
    redirect_to cart_items_url
  end

  private

    def cart_item_params
      params.require(:cart_item).permit(:user_id,:item_id,:amount)
    end

    def set_cart_items
      @cart_items = CartItem.where(user_id: current_user.id)
      @total_price = 0
      @total_amount = 0
    end
end

app/controllers/users/comments_controller.rb
class Users::CommentsController < ApplicationController

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      flash.now[:success] = "コメントを投稿しました！"
      @comments = @comment.item.comments.order(created_at: :desc)
    else
      flash.now[:denger] = "コメントが空欄です！"
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @comment = Comment.find_by(user_id: current_user.id, id: params[:id])
    @comments = @comment.item.comments.order(created_at: :desc)
    @comment.destroy
    flash.now[:success] = "コメントを削除しました！"
  end

  private

    def comment_params
      params.require(:comment).permit(:content).merge(item_id: params[:item_id])
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/items_controller.rb
class Users::ItemsController < ApplicationController
  before_action :authenticate_user!, except:[:index,:show]
  before_action :set_item, only:[:show,:edit,:update,:destroy]
  before_action :correct_user, only:[:edit,:update,:destroy]

  def new
    @item = Item.new
  end

  def index
    @items = Item.page(params[:page]).per(10)
    @genres = Genre.all
  end

  def show
    @cart_item = CartItem.new
    @like_count = Like.where(item_id: @item.id).count
    @comment = Comment.new
    @comments = @item.comments.order(created_at: :desc)
  end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      redirect_to @item, flash:{success: "商品を追加できました。"}
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to @item, flash:{success: "商品を編集できました。"}
    else
      render "edit"
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path
  end

  private
    def item_params
      params.require(:item).permit(:name,:introduction,
                    :genre_id,:price,:sales_status,:picture)
    end

    def set_item
      @item = Item.find(params[:id])
    end

    def correct_user
      if current_user.id != @item.user_id
        redirect_to @item, flash:[danger: "他のユーザの商品は編集できません。"]
      end
    end
end

app/controllers/users/likes_controller.rb
class Users::LikesController < ApplicationController
    before_action :authenticate_user!

    def index
        @like_items = current_user.like_items.page(params[:page]).per(20)
    end

    def create
        @like = current_user.likes.build(item_id: params[:item_id])
        @like.save
        @item = Item.find(@like.item_id)
        @like_count = Like.where(item_id: params[:item_id]).count
    end

    def destroy
        @like = Like.find_by(user_id: current_user.id, item_id: params[:item_id])
        @item = Item.find(@like.item_id)
        @like.destroy
        @like_count = Like.where(item_id: params[:item_id]).count
    end
    
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/orders_controller.rb
class Users::OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_orders, only:[:new]

  def new
  end

  def storage
    if params[:order][:payment_method].nil?
      flash.now[:danger] = "支払い方法を選択してください"
      set_orders
      render "new"
    else
      session[:order] = Order.new
      session[:order][:user_id] = current_user.id
      session[:order][:payment_method] = params[:order][:payment_method]
      session[:order][:total_payment] = product_price_calculation(current_user.cart_items) + session[:order][:shipping_cost]
      session[:select_address] = params[:order][:select_address]

      if session[:select_address] == "self"
        session[:order][:postcode] = current_user.postcode
        session[:order][:prefecture_name] = current_user.prefecture_name
        session[:order][:address] = current_user.address
        session[:order][:name] = current_user.last_name

      elsif session[:select_address] == "registered"
        address = Address.find(params[:order][:exis_address_id])
        session[:order][:postcode] = address.postcode
        session[:order][:prefecture_name] = address.prefecture_name
        session[:order][:address] = address.address
        session[:order][:name] = address.name

      elsif session[:select_address] == "new"
        session[:address] = Address.new
        session[:order][:postcode] = session[:address][:postcode] = params[:order][:postcode]
        session[:order][:prefecture_name] = session[:address][:prefecture_name] = params[:order][:prefecture_name]
        session[:order][:address] = session[:address][:address] = params[:order][:address]
        session[:order][:name] = session[:address][:name] = current_user.last_name
      
      end
      redirect_to confirm_orders_url
    end
  end

  def create
    if session[:select_address] == "new"
      address = current_user.addresses.build(session[:address])
      address.save
    end
    order = Order.new(session[:order])
    current_user.cart_items.each do |cart_item|
      order.order_details.build(
        item_id: cart_item.item.id,
        amount: cart_item.amount,
        purchase_price: cart_item.item.price
      )
    end
    order.save
    current_user.cart_items.destroy_all
    redirect_to complete_orders_url
  end

  def confirm
    @cart_items = current_user.cart_items
    @total_amount = 0
    @payment_status = session[:order]["payment_method"]
  end

  def complete
    session[:order].clear
  end

  def cancel
    session[:order].clear
    redirect_to root_url, flash: { success: "注文を中断しました" }
  end

  def index
  end

  def show
  end

  private

    # 購入商品の合計金額計算(送料なし)
    def product_price_calculation(cart_items)
        total = 0
        cart_items.each do |cart_item|
            total += (cart_item.item.price * 1.1).round * cart_item.amount
        end
        return total
    end

    def set_orders
      @order = Order.new
      @addresses = Address.where(user_id: current_user.id)
    end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  def after_sign_up_path_for(resource)
    user_path(resource)
  end

  def after_update_path_for(resource)
    user_path(resource)
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up,
      keys: [:name,:email,:password,:password_confirmation,:last_name,:first_name,
              :last_name_kana,:first_name_kana,:postcode,:prefecture_name,:address,
              :telephone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update,
      keys: [:name,:email,:password,:password_confirmation,:last_name,:first_name,
              :last_name_kana,:first_name_kana,:postcode,:prefecture_name,:address,
              :telephone_number])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource)
      items_path
  end

  def after_sign_out_path_for(resource)
      new_user_session_path
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users/addresses_helper.rb
module Users::AddressesHelper
end

app/views/users/orders/complete.html.erb
<h1>お買い上げありがとうございました！</h1>

<%= link_to "一覧に戻る", items_path, class: 'btn-pink' %>

app/views/users/orders/confirm.html.erb
<h2>商品内容</h2>
<table>
    <thead>
        <tr>
            <th>商品名</th>
            <th>価格(税込)</th>
            <th>数量</th>
            <th>小計</th>
        </tr>
    </thead>
    <tbody>
        <% @cart_items.each do |cart_item| %>
            <tr>
                <td><%= cart_item.item.name %></td>
                <td><%= (cart_item.item.price * 1.1).round %></td>
                <td><%= cart_item.amount %></td>
                <td><%= (cart_item.item.price * 1.1).round * cart_item.amount %></td>
            </tr>
            <% @total_amount += cart_item.amount %>
        <% end %>
    </tbody>
</table>

<div class="total-position">
    <h3>合計 (<%= @total_amount %>点) : ￥<%= session[:order]["total_payment"] %></h3>
</div>

<div class="box">
    <h3>支払い方法</h3>
    <b><%= t("enums.order.payment_method.#{@payment_status}") %></b>
</div>

<div class="box">
    <h3>お届け先</h3>
    <b>
        〒<%= session[:order]["postcode"] %>
        <%= session[:order]["address"] %>
        <%= session[:order]["name"] %>様
    </b>
</div>

<div class="btn-position">
    <%= link_to "注文を確定する", orders_path, method: :post, class: "btn-pink" %>
</div>

<div class="btn-position">
    <%= link_to "注文をキャンセルする", cancel_orders_path, method: :delete,
            data: { confirm: "本当に注文をキャンセルしますか？" }, class: "btn-yellow" %>
</div>

app/views/users/orders/index.html.erb
<h1>Users::Orders#index</h1>
<p>Find me in app/views/users/orders/index.html.erb</p>

app/views/users/orders/new.html.erb
<h2>注文情報入力画面</h2>

<%= form_with(model: @order, local: true, url: storage_orders_path) do |f| %>
    <%= render 'shared/error_messages', object: f.object%>

    <div class="box">
        <h3>支払い方法</h3>
        <div class="checkbox-inline">
            <% Order.payment_methods.each do |payment_method| %>
                <div class="checkbox">
                    <%= f.label :"payment_method_#{payment_method[0]}", t("enums.order.payment_method.#{payment_method[0]}") %>
                    <%= f.radio_button :payment_method, payment_method[0] %>
                </div>
            <% end %>
        </div>
    </div>

    <h3>お届け先</h3>
    <%= f.radio_button :select_address, :self, checked: true, onclick: "clickAddressBtn()" %>
    <%= f.label :select_address_self, "ご自身の住所" %><br>
        <div class="box">
            〒<%= current_user.postcode %>
            <%= current_user.prefecture_name %>
            <%= current_user.address %>
        </div>
        
    <% if @addresses.any? %>
        <%= f.radio_button :select_address, :registered, onclick: "clickAddressBtn()" %>
        <%= f.label :select_address_registered, "登録済住所から選択" %><br>
        <div id="form_1" class="form_container anime" style="display: none;">
            <div class="box_form">
                <div class="field">
                    <%= f.label :address, "住所", class: "form_label" %><br>
                    <%= f.collection_select :exis_address_id, @addresses, :id, :view_address, prompt: "住所を選択してください" %>
                </div>
            </div>
        </div>
    <% end %>
        
    <%= f.radio_button :select_address, :new, onclick: "clickAddressBtn()" %>
    <%= f.label :select_address_new, "新しいお届け先" %><br>

    <div id="form_2" class="form_container anime" style="display: none;">
        <div class="box_form">
            <div class="field">
                <%= f.label :postcode, "郵便番号", class: "form_label"%>
                <div class="form_post">
                    <%= f.text_field :postcode, maxlength: 7, autofocus: true, class: "form_input_post", placeholder: "例）1000001（ハイフンなし）" %>
                    <input type="button" id="btn" name="btn" value="住所を検索">
                </div>
            </div>  

            <div class="field">
                <%= f.label :prefecture_name, "都道府県", class: "form_label" %><br />
            　  <%= f.collection_select :prefecture_name, JpPrefecture::Prefecture.all, :name, :name, include_blank: "都道府県を選択してください" %>
            </div> 

            <div class="field">
                <%= f.label :address, "住所", class: "form_label" %><br />
                <%= f.text_field :address, autofocus: true, class: "form_content" %>   
            </div>
        </div>
    </div>
        
    <div class="btn-position">
        <%= f.submit "確認画面へ進む", class: "btn-pink" %>
    </div>

<% end %>

app/views/users/orders/show.html.erb
<h1>Users::Orders#show</h1>
<p>Find me in app/views/users/orders/show.html.erb</p>