config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'

  devise_scope :user do
    get 'login', to: 'users/sessions#new', as: :new_user_session
    post 'login', to: 'users/sessions#create', as: :user_session
    delete 'logout', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  devise_for :users, skip: [:sessions],
  controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  scope module: :users do
    resources :users, only:[:show,:edit,:update,:destroy]
    resources :items do
      resource :likes, only:[:create,:destroy]
      resources :comments, only:[:create,:update,:destroy]
    end
    resources :likes, only:[:index]
    resources :cart_items, only:[:index,:create,:update,:destroy] do
      collection do
        delete 'clear' # カートを空にする
      end
    end
    resources :orders, only:[:new,:index,:show,:create] do
      collection do
        get 'confirm'   # 購入情報確認画面
        post 'storage'  # セッションに保存
        get 'complete'  # 購入完了画面
        delete 'cancel' # 注文キャンセル
      end
    end
    resources :addresses, only:[:index,:create,:edit,:update,:destroy]
  end

  ######## 管理側 ########
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :admins do
    resources :items, only:[:edit,:update]
    resources :users, only:[:index,:show,:edit,:update,:destroy] do
      member do
        patch 'restore'
      end
    end
    resources :orders, only:[:index,:update,:show]
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details, dependent: :destroy
  
  enum payment_method: {
    bank_transfer: 0,
    credit_card_payment: 1,
    convenience_store_payment: 2,
    electronic_money_payment: 3,
    cash_on_delivery: 4
  }

  enum order_status: {
    waiting_for_payment: 0,
    payment_confirmation: 1,
    in_production: 2,
    preparing_for_shipment: 3,
    sent: 4
  }

  validates :payment_method, inclusion: {in: Order.payment_methods.keys}

end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.page(params[:page]).per(20)
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    order = Order.find(params[:id])
    if params[:order_status_commit]
      order.update(order_params)
    elsif params[:production_status_commit]
      OrderDetail.find(params[:order_detail][:id]).update(order_detail_params)
    else
      render "show"
    end
    redirect_to admins_orders_url, flash: { success: "ステータスを更新しました" }
  end

  private

    def order_params
      params.require(:order).permit(:order_status)
    end

    def order_detail_params
      params.require(:order_detail).permit(:production_status)
    end

end

app/controllers/users/orders_controller.rb
class Users::OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_orders, only:[:new]

  def new
  end

  def storage
    if params[:order][:payment_method].nil?
      flash.now[:danger] = "支払い方法を選択してください"
      set_orders
      render "new"
    else
      session[:order] = Order.new
      session[:order][:user_id] = current_user.id
      session[:order][:payment_method] = params[:order][:payment_method]
      session[:order][:total_payment] = product_price_calculation(current_user.cart_items) + session[:order][:shipping_cost]
      session[:select_address] = params[:order][:select_address]

      if session[:select_address] == "self"
        session[:order][:postcode] = current_user.postcode
        session[:order][:prefecture_name] = current_user.prefecture_name
        session[:order][:address] = current_user.address
        session[:order][:name] = current_user.last_name

      elsif session[:select_address] == "registered"
        address = Address.find(params[:order][:exis_address_id])
        session[:order][:postcode] = address.postcode
        session[:order][:prefecture_name] = address.prefecture_name
        session[:order][:address] = address.address
        session[:order][:name] = address.name

      elsif session[:select_address] == "new"
        session[:address] = Address.new
        session[:order][:postcode] = session[:address][:postcode] = params[:order][:postcode]
        session[:order][:prefecture_name] = session[:address][:prefecture_name] = params[:order][:prefecture_name]
        session[:order][:address] = session[:address][:address] = params[:order][:address]
        session[:order][:name] = session[:address][:name] = current_user.last_name
      
      end
      redirect_to confirm_orders_url
    end
  end

  def create
    if session[:select_address] == "new"
      address = current_user.addresses.build(session[:address])
      address.save
    end
    order = Order.new(session[:order])
    current_user.cart_items.each do |cart_item|
      order.order_details.build(
        item_id: cart_item.item.id,
        amount: cart_item.amount,
        purchase_price: cart_item.item.price
      )
    end
    order.save
    current_user.cart_items.destroy_all
    redirect_to complete_orders_url
  end

  def confirm
    @cart_items = current_user.cart_items
    @total_amount = 0
    @payment_status = session[:order]["payment_method"]
  end

  def complete
    session[:order].clear
  end

  def cancel
    session[:order].clear
    redirect_to root_url, flash: { success: "注文を中断しました" }
  end

  def index
  end

  def show
  end

  private

    # 購入商品の合計金額計算(送料なし)
    def product_price_calculation(cart_items)
        total = 0
        cart_items.each do |cart_item|
            total += (cart_item.item.price * 1.1).round * cart_item.amount
        end
        return total
    end

    def set_orders
      @order = Order.new
      @addresses = Address.where(user_id: current_user.id)
    end

end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/users/orders_helper.rb
module Users::OrdersHelper
end

app/views/admins/orders/index.html.erb
<h2>受注一覧</h2>

<% if @orders.any? %>
    <table>
        <thead>
            <tr>
                <th>お客様</th>
                <th>注文日時</th>
                <th>金額</th>
                <th>ステータス</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <% @orders.each do |order| %>
                <tr>
                    <td><%= order.name %></td>
                    <td><%= l order.created_at  %></td>
                    <td><%= order.total_payment %></td>
                    <td><%= order.order_status_i18n %></td>
                    <td><%= link_to "詳細", admins_order_path(order) %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <div class="pager">
        <%= paginate @orders %>
    </div>
<% else %>
    <h2>まだ受注されていません</h2>
<% end %>

app/views/admins/orders/show.html.erb
<h2>注文詳細</h2>

<h3>ご注文者情報</h3>
<table>
    <tr>
        <th>お客様</th>
        <td><%= @order.name %> 様</td>
    </tr>
    <tr>
        <th>配送先</th>
        <td>
            〒 <%= @order.postcode %>
            <%= @order.prefecture_name %>
            <%= @order.address %>
        </td>
    </tr>
    <tr>
        <th>支払い方法</th>
        <td><%= @order.payment_method_i18n %></td>
    </tr>
    <tr>
        <th>注文ステータス</th>
        <td>
            <%= form_with(model: @order, local: true, url: admins_order_path) do |f| %>
                <%= f.select :order_status, options_for_select_from_enum(Order, :order_status) %>
                <%= f.submit '更新', name: "order_status_commit" %>
            <% end %>
        </td>
    </tr>
</table>

<h3>製品情報</h3>
<table>
	<thead>
		<tr>
			<th>商品名</th>
			<th>価格(税込)</th>
			<th>購入数</th>
			<th>小計</th>
			<th>製作ステータス</th>
		</tr>
	</thead>
    <% @order.order_details.each do |order_detail| %>
	    <tbody>
            <tr>
                <td><%= order_detail.item.name %></td>
                <td><%= (order_detail.purchase_price * 1.1).round %></td>
                <td><%= order_detail.amount %></td>
                <td><%= (order_detail.purchase_price * 1.1).round * order_detail.amount %></td>
                <td>
                    <%= form_with(model: order_detail, local: true, url: admins_order_path) do |f| %>
                        <%= f.hidden_field :id, value: order_detail.id %>
                        <%= f.select :production_status, options_for_select_from_enum(OrderDetail, :production_status) %>
                        <%= f.submit '更新', name: "production_status_commit" %>
                    <% end %>
                </td>
            </tr>
	    </tbody>
    <% end %>
</table>